### ISSUE TITLE
Request to Ignore Custom Tags in OPML Files for Compatibility

### ISSUE THREAD

**Issue by Ashinch** [mdewilde/opml-parser#3]
Hi there,

I'm reaching out regarding an issue with the **opml-parser**. Some RSS reader applications tend to include custom tags in the exported OPML files for their own configuration backup and migration purposes. However, these custom tags are often irrelevant for other RSS readers.

The problem arises when the **opml-parser** enforces strict validation checks on these custom tags, resulting in it throwing exceptions like: `required element <outline> but found <xxx>`. 

https://github.com/mdewilde/opml-parser/blob/cc815143e2bbcee8a4481baa6a803ea57b9b63ab/src/main/java/be/ceau/opml/ValidityCheck.java#L36-L40

Is it possible for the **opml-parser** to ignore tags other than the necessary ones like <outline> during the parsing process? This would ensure compatibility with the majority of OPML files exported by various RSS reader applications available in the market.

Thank you for your work.

_Library version: [2.2.0]_
_Test file (replace with opml suffix): [feeder-export-2024-01-24T14_47_53.218.txt](https://github.com/mdewilde/opml-parser/files/14059947/feeder-export-2024-01-24T14_47_53.218.txt)_

**Comment by mdewilde** [comment]
Hi @Ashinch, thank you for the well documented request.

In the sample you provide, the problem is with the properly namespaced tag `feeder:settings`. 

The OPML spec actually allows for namespaced tags, as per http://opml.org/spec2.opml#1629042978000

I'd say then that the library is not compliant when it fails on these tags. I will make the necessary changes to allow these extensions. This should be ready soon.

My question for you is if this will completely cover your use case: are the problems you encounter (always) with properly namespaced tags in OPML files, or are there other examples that you would like me to consider?

**Comment by Ashinch** [comment]
> My question for you is if this will completely cover your use case: are the problems you encounter (always) with properly namespaced tags in OPML files, or are there other examples that you would like me to consider? 

Hi, @mdewilde

Based on my usage experience so far, I've only encountered this one issue, and it seems to work well in other cases. Thank you for your work!

**Comment by mdewilde** [comment]
Hi @Ashinch 
Sorry for the delay, I've been a bit under the weather.
I've just pushed version 3.1.0 which addresses the issue. It should become available through Maven Central in the next few minutes.
Please let me know if you run into any issues and thanks again for the change request.

**Comment by Ashinch** [comment]
> Hi @Ashinch Sorry for the delay, I've been a bit under the weather. I've just pushed version 3.1.0 which addresses the issue. It should become available through Maven Central in the next few minutes. Please let me know if you run into any issues and thanks again for the change request.

Hi, @mdewilde 

Verified, thank you for your work!
